name: CI – SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - uses: actions/checkout@v3

      # 2. Configura Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Instala las dependencias del proyecto + pytest + cobertura
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # 4. Ejecuta los tests con reporte de cobertura
      - name: Run tests with coverage
        run: |
          pytest --cov=a
